export const data = [
  {
    artist: 'Travis Scott',
    title: 'Stop Trying To Be God',
    song: './songs/travis-scott-stop-trying-to-be-god.mp3',
    cover: './res/astroworld.jpg',
  },
  {
    artist: 'Travis Scott',
    title: "Can't Say",
    song: './songs/travis-scott-cant-say.mp3',
    cover: './res/astroworld.jpg',
  },
  {
    artist: 'Travis Scott',
    title: 'Stargazing',
    song: './songs/travis-scott-stargazing.mp3',
    cover: './res/astroworld.jpg',
  },
  {
    artist: 'Skepta',
    title: 'Bullet From A Gun',
    song: './songs/skepta-bullet-from-a-gun.mp3',
    cover: './res/ignorance_is_bliss.png',
  },
  {
    artist: 'Skepta',
    title: 'Glow In The Dark',
    song: './songs/skepta-glow-in-the-dark.mp3',
    cover: './res/ignorance_is_bliss.png',
  },
  {
    artist: 'Skepta',
    title: 'Greeze Mode',
    song: './songs/skepta-greeze-mode.mp3',
    cover: './res/ignorance_is_bliss.png',
  },
  {
    artist: 'Skepta',
    title: 'What Do You Mean?',
    song: './songs/skepta-what-do-you-mean.mp3',
    cover: './res/ignorance_is_bliss.png',
  },
  {
    artist: 'A$AP Rocky',
    title: 'Changes',
    song: './songs/asap-rocky-changes.mp3',
    cover: './res/testing.jpg',
  },
  {
    artist: 'A$AP Rocky',
    title: 'Fuck Sleep',
    song: './songs/asap-rocky-fuck-sleep.mp3',
    cover: './res/testing.jpg',
  },
  {
    artist: 'A$AP Rocky',
    title: 'Kids Turned Out Fine',
    song: './songs/asap-rocky-kids-turned-out-fine.mp3',
    cover: './res/testing.jpg',
  },
  {
    artist: 'A$AP Rocky',
    title: 'Praise The Lord',
    song: './songs/asap-rocky-praise-the-lord.mp3',
    cover: './res/testing.jpg',
  },
  {
    artist: 'A$AP Rocky',
    title: 'Tony Tone',
    song: './songs/asap-rocky-tony-tone.mp3',
    cover: './res/testing.jpg',
  },
  {
    artist: 'Drake',
    title: "Can't Take A Joke",
    song: './songs/drake-cant-take-a-joke.mp3',
    cover: './res/scorpion.jpg',
  },
  {
    artist: 'Drake',
    title: "Don't Matter To Me",
    song: './songs/drake-dont-matter-to-me.mp3',
    cover: './res/scorpion.jpg',
  },
  {
    artist: 'Drake',
    title: 'Mob Ties',
    song: './songs/drake-mobties.mp3',
    cover: './res/scorpion.jpg',
  },
  {
    artist: 'Drake',
    title: 'Nice For What',
    song: './songs/drake-nice-for-what.mp3',
    cover: './res/scorpion.jpg',
  },
  {
    artist: 'Drake',
    title: 'Nonstop',
    song: './songs/drake-nonstop.mp3',
    cover: './res/scorpion.jpg',
  },
  {
    artist: 'Kendrick Lamar',
    title: 'DNA',
    song: './songs/kendrick-lamar-dna.mp3',
    cover: './res/damn.jpg',
  },
  {
    artist: 'Kendrick Lamar',
    title: 'ElEMENT',
    song: './songs/kendrick-lamar-element.mp3',
    cover: './res/damn.jpg',
  },
  {
    artist: 'Kendrick Lamar',
    title: 'FEEL',
    song: './songs/kendrick-lamar-feel.mp3',
    cover: './res/damn.jpg',
  },
  {
    artist: 'Kendrick Lamar',
    title: 'GOD',
    song: './songs/kendrick-lamar-god.mp3',
    cover: './res/damn.jpg',
  },
  {
    artist: 'Kendrick Lamar',
    title: 'HUMBLE',
    song: './songs/kendrick-lamar-humble.mp3',
    cover: './res/damn.jpg',
  },
  {
    artist: 'Kendrick Lamar',
    title: 'Money Trees',
    song: './songs/kendrick-lamar-money-trees.mp3',
    cover: './res/goodkid_maad_city.jpg',
  },
  {
    artist: 'Kendrick Lamar',
    title: 'PRIDE',
    song: './songs/kendrick-lamar-pride.mp3',
    cover: './res/damn.jpg',
  },
  {
    artist: 'Kendrick Lamar',
    title: 'Sing About Me/Dying Of Thirst',
    song: './songs/kendrick-lamar-sing-about-me.mp3',
    cover: './res/goodkid_maad_city.jpg',
  },
  {
    artist: 'Kendrick Lamar',
    title: 'Swimming Pools',
    song: './songs/kendrick-lamar-swimming-pools.mp3',
    cover: './res/goodkid_maad_city.jpg',
  },
  {
    artist: 'Kendrick Lamar',
    title: 'Art Of Peer Pressure',
    song: './songs/kendrick-lamar-art-of-peer-pressure.mp3',
    cover: './res/goodkid_maad_city.jpg',
  },
  {
    artist: 'Post Malone',
    title: 'Better Now',
    song: './songs/post-malone-better-now.mp3',
    cover: './res/beerbong&bentleys.jpg',
  },
  {
    artist: 'Post Malone',
    title: 'Blame It On Me',
    song: './songs/post-malone-blame-it-on-me.mp3',
    cover: './res/beerbong&bentleys.jpg',
  },
  {
    artist: 'Post Malone',
    title: 'Otherside',
    song: './songs/post-malone-otherside.mp3',
    cover: './res/beerbong&bentleys.jpg',
  },
  {
    artist: 'The Weeknd',
    title: 'Call Out My Name',
    song: './songs/theweeknd-call-out-my-name.mp3',
    cover: './res/my_dear-melancholy.jpg',
  },
]
